
version: "3"

services:
  backend:
    build: interface_backend/
    command: python ./app.py
    ports:
      - 5000:5000

  client:
    build: interface_app/
    network_mode: host
    depends_on:
      - backend
    ports:
    - 8080:80